version = 1

# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Licensing statement required for linting to pass for this repository

# JSON allows no comments, so this cannot carry an inline header
[[annotations]]
path = "tsconfig.json"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2026 The Linux Foundation"

[[annotations]]
path = [
     "app/**",
     "package-lock.json",
     "package.json"
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileCopyrightText = "2025 The Linux Foundation"
