---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - '**'
      - '!.github/**'
      - '!.*'
      - '!tox.ini'

permissions: {}

jobs:
  ### Test the project in this repository ###
  tests:
    name: "Build/test example project code"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: "Build/test node example project 🛠️"
        shell: bash
        run: |
          # Build/test node example project
          echo "Building/testing example project"
          node -v
          npm install
          npm test
